# Permalinks
permalink:        /post/:title.html

# Setup
url:              https://blog.augustrush8.com
img_url:          http://pkngrra8q.bkt.clouddn.com

# Set to '' in case of hosting on `https://<your-github-name>.github.io`
baseurl:          ''

title:            'August Rush'

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  关于[代码](https://github.com/AUGUSTRUSH8)、生活、爱和一切。


# Fallback image and color if not overwritten for tag or post
image:            /public/images/sunset.jpg
color:            '#dc322f'


author:
  name:           'AugustRush'
  email:          643098432@qq.com
  github:         AugustRush8
  twitter:        tianhang12
  weibo:          u/5065802307
  photo:          /public/images/logo.jpg


  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    我是August Rush，热爱编程，喜欢与人交流分享思想和 IT 技术。我的GitHub地址是 [AugustRush](https://github.com/AUGUSTRUSH8)


compress_html:
  clippings:      all
  comments:       ["<!--", "-->"]
  endings:        all
  startings:      [html, head, body]

sass:
  sass_dir:       /public/css
  style:          compressed
